name: deno

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Lint wrapper
        run: deno lint deno/

      - name: Format check wrapper
        run: deno fmt --check deno/

      - name: Run envinfo via Deno (JSON)
        run: deno run --allow-run --allow-read --allow-env --allow-sys deno/envinfo.ts --system --binaries --json

